apiVersion: v1
kind: Namespace
metadata:
  name: bloodstream-demo
  labels:
    bloodstream.io/component: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: bloodstream
  labels:
    bloodstream.io/component: control-plane
