apiVersion: bloodstream.io/v1
kind: BloodstreamPath
metadata:
  name: playwright-docs
  namespace: bloodstream
spec:
  services:
    - playwright.dev
  configs:
    - chrome-latest
    - default-feature-flags
    - staging-env
    - safari
    - firefox
    - android-low-end
    - slow-network
    - feature-flag-alt-checkout
    - degraded-payment-provider
    - old-ui-version
